image:
  name: registry.gitlab.com/partisia/dockerimages/mkdocs:latest
variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
- prepare
- build
- deploy

prepare-zip:
  image: registry.gitlab.com/partisia/dockerimages/rust:latest
  stage: prepare
  only:
    refs:
    - main
    changes:
    - sdk-version.txt
  script:
  - ./build-zip.sh

prepare-zip-dev:
  image: registry.gitlab.com/partisia/dockerimages/rust:latest
  stage: prepare
  except:
  - main
  script:
  - ./build-zip.sh

build-site:
  stage: build
  script:
  - mkdocs build --site-dir public --strict
  artifacts:
    paths:
    - public

pages:
  image: registry.gitlab.com/partisia/dockerimages/rust:latest
  stage: deploy
  dependencies:
  - build-site
  script:
  - ./replace-zip-version.sh
  only:
  - main
  artifacts:
    paths:
    - public

pages-dev:
  image: registry.gitlab.com/partisia/dockerimages/rust:latest
  stage: deploy
  dependencies:
  - build-site
  script:
  - ./replace-zip-version.sh
  - 'echo "Pages URL: ${CI_JOB_URL}/artifacts/file/public/index.html"'
  except:
  - main
  artifacts:
    paths:
    - public
