image:
  name: registry.gitlab.com/partisia/dockerimages/mkdocs:latest
variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
- prepare
- build
- deploy

build-site:
  stage: build
  script:
  - mkdocs build --site-dir public --strict
  artifacts:
    paths:
    - public

pages:
  image: registry.gitlab.com/partisia/dockerimages/rust:latest
  stage: deploy
  dependencies:
  - build-site
  script:
  only:
  - main
  artifacts:
    paths:
    - public

pages-dev:
  image: registry.gitlab.com/partisia/dockerimages/rust:latest
  stage: deploy
  dependencies:
  - build-site
  script:
  - 'echo "Pages URL: ${CI_JOB_URL}/artifacts/file/public/index.html"'
  except:
  - main
  artifacts:
    paths:
    - public
