image:
  name: registry.gitlab.com/partisia/dockerimages/mkdocs:latest
variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - prepare
  - build
  - deploy

build-site:
  stage: build
  script:
    - mkdocs build --site-dir public --strict
  artifacts:
    paths:
      - public

pages:
  image: registry.gitlab.com/partisia/dockerimages/mkdocs:latest
  stage: deploy
  dependencies:
    - build-site
  script:
    - 'echo "Pages URL: ${CI_JOB_URL}/artifacts/file/public/index.html"'
  only:
    - main
  artifacts:
    paths:
      - public

pages-dev:
  image: registry.gitlab.com/partisia/dockerimages/mkdocs:latest
  stage: deploy
  dependencies:
    - build-site
  script:
    - 'echo "Pages URL: ${CI_JOB_URL}/artifacts/file/public/index.html"'
  except:
    - main
  artifacts:
    paths:
      - public

dead-link-check:
  image: registry.gitlab.com/partisia/dockerimages/shellscripting
  stage: deploy
  dependencies:
    - build-site
  except:
    - main
  allow_failure: true
  script:
    - apt update && apt install -y linkchecker
    - linkchecker -t 8 --no-robots --check-extern --ignore-url="https://reader\.partisiablockchain\.com.*" --ignore-url="/builds/partisiablockchain.*" --ignore-url="/documentation/node-operations/what-is-a-node-operator.html" --ignore-url="/documentation/index.html" --ignore-url="https://twitter.com/partisiampc" --ignore-url="/documentation/smart-contracts/introduction-to-smart-contracts.html" public/index.html
  artifacts:
    paths:
      - public

spellcheck:
  image: registry.gitlab.com/partisia/dockerimages/shellscripting
  stage: build
  dependencies:
    - build-site
  except:
    - main
  script:
    - apt update && apt install -y aspell
    - shopt -s globstar
    - |
      touch maybe-misspelled-words.txt
      for file in **/*.md; do
        echo "Spellchecking $file"
        echo "------"
        cat "$file" | aspell --mode markdown -d en_US --personal=config/partisias_word_list.txt --home-dir=. list -v | sort -f | uniq -i | tee -a maybe-misspelled-words.txt || true
        echo -e "\033[30m-\033[0m"
        echo -e "\033[30m-\033[0m"
      done

      echo -e "\033[30m-\033[0m"
      echo -e "\033[30m-\033[0m"

      echo "All unique potentially misspelled words, sorted:"
      echo "------"
      cat maybe-misspelled-words.txt | sort -f | uniq -i

.npm:
  image: registry.gitlab.com/partisia/dockerimages/node-20
  before_script:
    - cd "$NPM_WORK_DIR" || exit
    - echo -e "$NPM_CI_CONFIG" > .npmrc
  needs:
    - job: before-typescript
      optional: true
  cache:
    key: npm-cache
    policy: pull-push
    paths:
      - npm-cache

npm-install:
  extends: .npm
  stage: build
  script:
    - npm ci --cache npm-cache --prefer-offline
    - '[[ -d "node_modules/" ]]'
  artifacts:
    expire_in: 1 day
    paths:
      - "${NPM_WORK_DIR}/node_modules/"

prettier:
  extends: .npm
  stage: test
  needs:
    - job: before-typescript
      optional: true
    - job: npm-install
  script:
    - npx prettier
      --print-width 100
      --tab-width 2
      --quote-props as-needed
      --trailing-comma es5
      --bracket-same-line
      --prose-wrap preserve
      --end-of-line lf
      --check src
