image:
  name: registry.gitlab.com/partisia/dockerimages/mkdocs:latest
variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
- prepare
- build
- deploy

build-site:
  stage: build
  script:
  - mkdocs build --site-dir public --strict
  artifacts:
    paths:
    - public

pages:
  image: registry.gitlab.com/partisia/dockerimages/mkdocs:latest
  stage: deploy
  dependencies:
  - build-site
  script:
  - 'echo "Pages URL: ${CI_JOB_URL}/artifacts/file/public/index.html"'
  only:
  - main
  artifacts:
    paths:
    - public

pages-dev:
  image: registry.gitlab.com/partisia/dockerimages/mkdocs:latest
  stage: deploy
  dependencies:
  - build-site
  script:
  - 'echo "Pages URL: ${CI_JOB_URL}/artifacts/file/public/index.html"'
  except:
  - main
  artifacts:
    paths:
    - public

dead-link-check:
  image: registry.gitlab.com/partisia/dockerimages/shellscripting
  stage: deploy
  dependencies:
  - build-site
  except:
  - main
  when: manual
  allow_failure: true
  script:
  - apt update && apt install -y linkchecker
  - linkchecker -t 8 --no-robots --check-extern public/index.html
  artifacts:
    paths:
    - public

spellcheck-changed:
  image: registry.gitlab.com/partisia/dockerimages/shellscripting
  stage: deploy
  dependencies:
  - build-site
  except:
  - main
  allow_failure: true
  script:
  - apt update && apt install -y aspell
  - MD_FILES=$(git diff --name-status "$CI_MERGE_REQUEST_TARGET_BRANCH_NAME" | grep -v -E '^D\s.*' | grep ".md" | awk '{ print $NF }')
  - |
    readarray -t files <<<"$(shfmt -f .)"
    for (( i = 0; i < "${#files[@]}"; i++ )); do
      local file="${files[i]}"
      echo "Spellchecking $file"
      echo "------"
      cat "$file" | aspell --mode markdown -d en_US list | sort | uniq -i || true
      echo -e "\033[30m-\033[0m"
      echo -e "\033[30m-\033[0m"
    done

spellcheck-all:
  image: registry.gitlab.com/partisia/dockerimages/shellscripting
  stage: deploy
  dependencies:
  - build-site
  except:
  - main
  allow_failure: true
  script:
  - apt update && apt install -y aspell
  - shopt -s globstar
  - |
    touch maybe-misspelled-words.txt
    for file in **/*.md; do
      echo "Spellchecking $file"
      echo "------"
      cat "$file" | aspell --mode -H -d en_US --personal=config/partisias_word_list.txt --home-dir=. list -v | sort -f | uniq -i | tee -a maybe-misspelled-words.txt || true
      echo -e "\033[30m-\033[0m"
      echo -e "\033[30m-\033[0m"
    done

    echo -e "\033[30m-\033[0m"
    echo -e "\033[30m-\033[0m"

    echo "All unique potentially misspelled words, sorted:"
    echo "------"
    cat maybe-misspelled-words.txt | sort -f | uniq -i

