site_name: Partisia Blockchain
site_url:
use_directory_urls: False
nav:
  - Home: meta-page/index.md
  - PBC Fundamentals:
      - Introduction to the Partisia Blockchain fundamentals: pbc-fundamentals/introduction.md
      - Create an account on Partisia Blockchain (PBC): pbc-fundamentals/accounts.md
      - BYOC and gas for the mainnet and testnet: pbc-fundamentals/byoc.md
      - $MPC token model and Account Elements: pbc-fundamentals/mpc-tokens.md
      - Partisia Blockchain Dictionary: pbc-fundamentals/dictionary.md
  - Develop PBC Smart contracts, tools and Samples:
      - Introduction to smart contracts: smart-contracts/smart-contracts.md
      - What is a smart contract: smart-contracts/contract-development.md
      - Install the smart contract compiler: smart-contracts/download-compiler.md
      - Compile and deploy contracts: smart-contracts/contract-compilation.md
      - Access and use the testnet: smart-contracts/testnet.md
      - Public and ZK Smart Contract examples - Combine and innovate: smart-contracts/combi-innovation.md
      - Programmers Guide to PBC smart contracts: smart-contracts/programmers_guide.md
      - Partisia Blockchain Smart Contract Binary Formats: smart-contracts/abiv.md
      - How to create a smart contract with a specific scenario: smart-contracts/voting-contract.md
      - Zero Knowledge Smart Contracts: smart-contracts/ZKSC.md
      - Compile Zero Knowledge Contracts: smart-contracts/compile-zk.md
      - Zero Knowledge Gas Fees: smart-contracts/zk-computation-fees.md
      - Zero Knowledge Rust Language (ZkRust):
          - ZkRust Language: smart-contracts/zk-language.md
          - ZK Rust Reference: smart-contracts/zk-language-reference.md
          - Zk language features: smart-contracts/zk-language-features.md
      - Development FAQ: smart-contracts/dev-faq.md
  - Run a node:
      - What is a node operator: node-operations/operator-0-introduction.md
      - Specs: node-operations/operator-1-specs.md
      - Local reader: node-operations/operator-2-reader.md
      - VPS: node-operations/operator-3-vps.md
      - VPS security: node-operations/operator-4-security.md
      - Reader node on VPS: node-operations/operator-5-reader-vps.md
      - Create a PBC account: node-operations/operator-6-create-account.md
      - Get MPC tokens: node-operations/operator-7-get-mpc-tokens.md
      - Complete Synaps KYB: node-operations/operator-8-synaps.md
      - Keys for BP config and registration: node-operations/operator-9-keys.md
      - Change node config from reader to block producer: node-operations/operator-10-bp.md
      - Register your node in the MPC Explorer: node-operations/operator-11-registration.md
      - Node health and maintenance: node-operations/operator-12-node-health.md
      - Update your node's public information: node-operations/update-transaction.md
      - REST API documentation: https://partisiablockchain.gitlab.io/documentation/rest
  - Get support from PBC community: meta-page/support.md

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - js/mermaid.min.js
  - js/polyfill.min.js
  - js/extra.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight
  - pymdownx.superfences:
      # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format

plugins:
  - search
  - mermaid2:
      arguments:
        securityLevel: "loose"
        theme: forest # we want also that to work

theme:
  logo: assets/pbclogo.png
  favicon: assets/pbclogo_with_background.png
  name: material
  custom_dir: overrides
  features:
    - navigation.indexes

extra:
  generator: true
  homepage: https://www.partisiablockchain.com/
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/partisiampc
    - icon: fontawesome/brands/telegram
      link: https://t.me/partisiampc
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/5HX7j9xFS7
    - icon: fontawesome/brands/medium
      link: https://medium.com/partisia-blockchain
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/c/PARTISIABLOCKCHAINFOUNDATION
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/privacy-blockchain/?viewAsMember=true

copyright: Partisia Blockchain All Rights Reserved &copy; 2022
