site_name: Partisia BlockChain
nav:
  - Home: index.md
  - Latest developments:
      News for Node Operators: newkeypair.md
      Launch of MainNet: mainnet.md
  - Concepts: 
      Transactions: transactions.md
      Contract development: contract-development.md
      Zero knowledge contracts: vickrey.md
      Accounts: accounts.md
      BYOC and gas: byoc.md
      Blocks: block.md
      Shards: shards
      Public key cryptography: keys.md
  - Getting started as a node operator:
      Running a PBC node: operator.md
      The keys you need: newkeypair.md
      REST API documentation: rest
  - Getting started as a developer:
      What is a smart contract - token contract example: contract-development.md
      Create a smart contract for a specific scenario: voting-contract.md
      Zero Knowledge Contract - vickrey auction example: vickrey.md


extra_css:
  - stylesheets/extra.css

extra_javascript:
  - js/mermaid.min.js
  - js/mathjax-conf.js
  - js/polyfill.min.js
  - js/tex-mml-chtml.js


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight
  - pymdownx.superfences:
      # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          #format: !!python/name:mermaid2.fence_mermaid_custom
          format: !!python/name:pymdownx.superfences.fence_div_format

plugins:
    - search
    - mermaid2:
        arguments:
          securityLevel: 'loose'
          theme: forest # we want also that to work


theme:
  logo: assets/pbclogo.png
  favicon: assets/pbclogo.png
  name: material
  features:
    - toc.integrate
    - navigation.expand
    - navigation.sections
    - navigation.instant
  # palette:
  #   - scheme: default
  #     primary: indigo
  #     accent: indigo
  #     toggle:
  #       icon: material/toggle-switch-off-outline
  #       name: Switch to dark mode
  #   - scheme: slate
  #     primary: red
  #     accent: red
  #     toggle:
  #       icon: material/toggle-switch
  #       name: Switch to light mode
