site_name: Privacy BlockChain
nav:
  - Home: index.md
  - Concepts: 
      Transactions: transactions.md
      Accounts: accounts.md
      Blocks: block.md
      Shards: shards
      Public key cryptography: keys.md
  - Running a node:
      Getting started: operator.md
  

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - js/mermaid.min.js

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences:
      # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          #format: !!python/name:mermaid2.fence_mermaid_custom
          format: !!python/name:pymdownx.superfences.fence_div_format

plugins:
    - search
    - mermaid2:
        arguments:
          securityLevel: 'loose'
          theme: forest # we want also that to work

markdown_extensions:
  - toc:
      toc_depth: 3

theme:
  name: material
  features:
    - toc.integrate
    - navigation.expand
    - navigation.sections