site_name: Partisia Blockchain
site_url:
use_directory_urls: False
nav:
  - Home: index.md
  - Run a node:
      - What is a node operator: operator-0-introduction.md
      - Specs: operator-1-specs.md
      - Local reader: operator-2-reader.md
      - VPS: operator-3-vps.md
      - VPS security: operator-4-security.md
      - Reader node on VPS: operator-5-reader-vps.md
      - Create a PBC account: operator-6-create-account.md
      - Get MPC tokens: operator-7-get-mpc-tokens.md
      - Complete Synaps KYB: operator-8-synaps.md
      - Keys for BP config and registration: operator-9-keys.md
      - Change node config from reader to block producer: operator-10-bp.md
      - Register your node in the MPC Explorer: operator-11-registration.md
      - Node health and maintenance: operator-12-node-health.md
      - Update your node's public information: update-transaction.md
      - REST API documentation: https://partisiablockchain.gitlab.io/documentation/rest
  - Downloadable resources:
      - Smart Contract compiler: download-compiler.md
      - Public and ZK Smart Contract examples: combi-innovation.md
  - Develop smart contracts:
      - What is a smart contract: contract-development.md
      - Download compiler for contract development: download-compiler.md
      - Compile and deploy contracts: contract-compilation.md
      - MPC Examples and Smart contracts available for combinatorial innovation: combi-innovation.md
      - Programmer's Guide to PBC smart contract: programmers_guide.md
      - ABI specification: abiv.md
      - Create a smart contract for a specific scenario: voting-contract.md
      - Zero Knowledge Contracts: ZKSC.md
      - Compile Zero Knowledge Contracts: compile-zk.md
      - Zero Knowledge Gas Fees: zk-computation-fees.md
      - ZkRust Language: zk-language.md
      - Development FAQ: dev-faq.md
  - PBC's decoupled token economy:
      - BYOC and gas for the mainnet and testnet: byoc.md
      - MPC token model: mpc-tokens.md
  - Terminology:
      - PBC Dictionary: dictionary.md


extra_css:
  - stylesheets/extra.css
  - stylesheets/nav.css

extra_javascript:
  - js/mermaid.min.js
  - js/polyfill.min.js
  - js/extra.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight
  - pymdownx.superfences:
      # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format

plugins:
    - search
    - mermaid2:
        arguments:
          securityLevel: 'loose'
          theme: forest # we want also that to work

theme:
  logo: assets/pbclogo.png
  favicon: assets/pbclogo_with_background.png
  name: material
  custom_dir: overrides
  features:
  - navigation.indexes

extra:
  generator: true
  homepage: https://www.partisiablockchain.com/
  social:
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/partisiampc
  - icon: fontawesome/brands/telegram
    link: https://t.me/partisiampc
  - icon: fontawesome/brands/discord
    link: https://discord.com/invite/5HX7j9xFS7
  - icon: fontawesome/brands/medium
    link: https://medium.com/partisia-blockchain
  - icon: fontawesome/brands/youtube
    link: https://youtube.com/c/PARTISIABLOCKCHAINFOUNDATION
  - icon: fontawesome/brands/linkedin
    link: https://www.linkedin.com/company/privacy-blockchain/?viewAsMember=true

copyright: Partisia Blockchain All Rights Reserved &copy; 2022
