site_name: Privacy BlockChain
nav:
  - Home: index.md
  - Accounts: accounts.md
  - Public key cryptography: keys.md
  - Transactions: transactions.md
  - Node operator: operator.md

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - js/mermaid.min.js

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences:
      # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          #format: !!python/name:mermaid2.fence_mermaid_custom
          format: !!python/name:pymdownx.superfences.fence_div_format

plugins:
    - search
    - mermaid2:
        arguments:
          securityLevel: 'loose'
          theme: forest # we want also that to work
