site_name: Partisia Blockchain (PBC)
site_url: https://partisiablockchain.gitlab.io/documentation
repo_url: https://partisiablockchain.gitlab.io/documentation
use_directory_urls: False
nav:
  - PBC fundamentals:
      - pbc-fundamentals/introduction-to-the-fundamentals.md
      - pbc-fundamentals/create-an-account.md
      - pbc-fundamentals/byoc-and-gas-for-the-mainnet-and-testnet.md
      - pbc-fundamentals/mpc-token-model-and-account-elements.md
      - pbc-fundamentals/dictionary.md
  - Develop smart contracts, tools and examples:
      - smart-contracts/introduction-to-smart-contracts.md
      - smart-contracts/what-is-a-smart-contract.md
      - smart-contracts/install-the-smart-contract-compiler.md
      - smart-contracts/compile-and-deploy-contracts.md
      - smart-contracts/access-and-use-the-testnet.md
      - smart-contracts/smart-contract-examples.md
      - smart-contracts/programmers-guide-to-smart-contracts.md
      - smart-contracts/smart-contract-binary-formats.md
      - smart-contracts/how-to-create-a-vote-from-a-smart-contract.md
      - Zero Knowledge (ZK) Smart Contracts:
          - smart-contracts/zk-smart-contracts.md
          - smart-contracts/compile-and-deploy-zk-contract.md
          - smart-contracts/zk-computation-gas-fees.md
          - smart-contracts/zk-rust-language-zkrust.md
          - smart-contracts/zk-rust-reference.md
          - smart-contracts/zk-language-features.md
      - smart-contracts/pbc-as-second-layer/partisia-blockchain-as-second-layer.md
      - smart-contracts/development-faq.md
  - Run a node:
      - node-operations/what-is-a-node-operator.md
      - node-operations/recommended-hardware-and-software.md
      - node-operations/run-a-reader-node-on-your-local-machine.md
      - node-operations/vps.md
      - node-operations/secure-your-vps.md
      - node-operations/reader-node-on-vps.md
      - node-operations/create-an-account-on-pbc.md
      - node-operations/get-mpc-tokens.md
      - node-operations/operator-8-synaps.md
      - node-operations/operator-9-keys.md
      - node-operations/operator-10-bp.md
      - node-operations/operator-11-registration.md
      - node-operations/operator-12-node-health.md
      - node-operations/update-transaction.md
      - REST API documentation: https://partisiablockchain.gitlab.io/documentation/rest
  - get-support-from-PBC-community.md

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - js/mermaid.min.js
  - js/polyfill.min.js
  - js/extra.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight
  - pymdownx.superfences:
      # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format

plugins:
  - search
  - mermaid2:
      arguments:
        securityLevel: "loose"
        theme: forest # we want also that to work

theme:
  logo: assets/pbclogo.png
  favicon: assets/pbclogo_with_background.png
  name: material
  custom_dir: overrides
  features:
    - navigation.indexes

extra:
  generator: true
  homepage: https://www.partisiablockchain.com/
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/partisiampc
    - icon: fontawesome/brands/telegram
      link: https://t.me/partisiampc
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/5HX7j9xFS7
    - icon: fontawesome/brands/medium
      link: https://medium.com/partisia-blockchain
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/c/PARTISIABLOCKCHAINFOUNDATION
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/privacy-blockchain/?viewAsMember=true

copyright: Partisia Blockchain All Rights Reserved &copy; 2022
