site_name: Partisia Blockchain
site_url:
use_directory_urls: False
nav:
  - Home: index.md
  - PBC Fundamentals:
      - Introduction to the Partisia Blockchain fundamentals: /docs/PBCFundamentals/introduction.md
      - Create an account on Partisia Blockchain (PBC): accounts.md
      - BYOC and gas for the mainnet and testnet: byoc.md
      - $MPC token model and Account Elements: mpc-tokens.md
      - Partisia Blockchain Dictionary: dictionary.md
  - Develop PBC Smart contracts, tools and Samples:
      - Introduction to smart contracts: smart-contracts.md
      - What is a smart contract: contract-development.md
      - Install the smart contract compiler: download-compiler.md
      - Compile and deploy contracts: contract-compilation.md
      - Access and use the testnet: testnet.md
      - Public and ZK Smart Contract examples - Combine and innovate: combi-innovation.md
      - Programmers Guide to PBC smart contracts: programmers_guide.md
      - Partisia Blockchain Smart Contract Binary Formats: abiv.md
      - How to create a smart contract with a specific scenario: voting-contract.md
      - Zero Knowledge Smart Contracts: ZKSC.md
      - Compile Zero Knowledge Contracts: compile-zk.md
      - Zero Knowledge Gas Fees: zk-computation-fees.md
      - Zero Knowledge Rust Language (ZkRust):
          - ZkRust Language: zk-language.md
          - ZK Rust Reference: zk-language-reference.md
          - Zk language features: zk-language-features.md
      - Development FAQ: dev-faq.md
  - Run a node:
      - What is a node operator: NodeOperations/operator-0-introduction.md
      - Specs: NodeOperations/operator-1-specs.md
      - Local reader: NodeOperations/operator-2-reader.md
      - VPS: NodeOperations/operator-3-vps.md
      - VPS security: NodeOperations/operator-4-security.md
      - Reader node on VPS: NodeOperations/operator-5-reader-vps.md
      - Create a PBC account: NodeOperations/operator-6-create-account.md
      - Get MPC tokens: NodeOperations/operator-7-get-mpc-tokens.md
      - Complete Synaps KYB: NodeOperations/operator-8-synaps.md
      - Keys for BP config and registration: NodeOperations/operator-9-keys.md
      - Change node config from reader to block producer: NodeOperations/operator-10-bp.md
      - Register your node in the MPC Explorer: NodeOperations/operator-11-registration.md
      - Node health and maintenance: NodeOperations/operator-12-node-health.md
      - Update your node's public information: NodeOperations/update-transaction.md
      - REST API documentation: https://partisiablockchain.gitlab.io/documentation/rest
  - Get support from PBC community: support.md

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - js/mermaid.min.js
  - js/polyfill.min.js
  - js/extra.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight
  - pymdownx.superfences:
      # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format

plugins:
  - search
  - mermaid2:
      arguments:
        securityLevel: "loose"
        theme: forest # we want also that to work

theme:
  logo: assets/pbclogo.png
  favicon: assets/pbclogo_with_background.png
  name: material
  custom_dir: overrides
  features:
    - navigation.indexes

extra:
  generator: true
  homepage: https://www.partisiablockchain.com/
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/partisiampc
    - icon: fontawesome/brands/telegram
      link: https://t.me/partisiampc
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/5HX7j9xFS7
    - icon: fontawesome/brands/medium
      link: https://medium.com/partisia-blockchain
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/c/PARTISIABLOCKCHAINFOUNDATION
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/privacy-blockchain/?viewAsMember=true

copyright: Partisia Blockchain All Rights Reserved &copy; 2022
