site_name: Partisia BlockChain
nav:
  - Home: index.md
  - Getting started as a Node Operator:
      What is a Node Operator: whatisano.md
      How to become a Node Operator: bpinclusion.md
      Creating the keys: newkeypair.md
      Running a PBC Node: operator.md
      REST API documentation: rest
  - Getting started as a developer:
      What is a smart contract and why develop on PBC: contract-development.md
      Develop your first contract - token contract example: token-contract.md
      Programmer's Guide to PBC SDK: programmers_guide.md
      ABI specification: abiv1.md
      Create a smart contract for a specific scenario: voting-contract.md
  - Zero knowledge contracts:
      Zero Knowledge Contract - vickrey auction example: vickrey.md
  - Economic Ecosystem:
      Accounts: accounts.md
      BYOC and gas: byoc.md
      MPC tokens: mpc-tokens.md
  - Concepts:
      Transactions: transactions.md
      Blocks: block.md
      Consensus Model: consensus.md
      Shards: shards.md
      Public key cryptography: keys.md


extra_css:
  - stylesheets/extra.css

extra_javascript:
  - js/mermaid.min.js
  - js/polyfill.min.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight
  - pymdownx.superfences:
      # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format

plugins:
    - search
    - mermaid2:
        arguments:
          securityLevel: 'loose'
          theme: forest # we want also that to work


theme:
  logo: assets/pbclogo.png
  favicon: assets/pbclogo_with_background.png
  name: material
  features:
    - toc.integrate
    - navigation.expand
    - navigation.sections
    - navigation.instant
