site_name: Partisia Blockchain
site_url:
use_directory_urls: False
nav:
  - Home: index.md
  - Getting started as a Node Operator:
      What is a Node Operator: whatisano.md
      Run a node - introduction and index: operator-0-introduction.md
      Run a node 1: operator-1-specs.md
      Run a node 2: operator-2-reader.md
      Run a node 3: operator-3-vps.md
      Run a node 4: operator-4-security.md
      Run a node 5: operator-5-reader-vps.md
      Run a node 6: operator-6-keys.md
      Run a node 7: operator-7-bp.md
      Run a node 8: operator-8-registration.md
      REST API documentation: https://partisiablockchain.gitlab.io/documentation/rest
  - Getting started as a developer:
      What is a smart contract: contract-development.md
      Develop your first contract - token contract example: token-contract.md
      Programmer's Guide to PBC SDK: programmers_guide.md
      ABI 4.0 specification: abiv_latest.md
      ABI 3.1 specification: abiv3_1.md
      Create a smart contract for a specific scenario: voting-contract.md
      Zero Knowledge Contracts: vickrey.md
  - Concepts:
      Accounts: accounts.md
      BYOC and gas: byoc.md
      MPC tokens: mpc-tokens.md
      Transactions: transactions.md
      Blocks: block.md
      Consensus Model: consensus.md
      Shards: shards.md
      Public key cryptography: keys.md


extra_css:
  - stylesheets/extra.css

extra_javascript:
  - js/mermaid.min.js
  - js/polyfill.min.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight
  - pymdownx.superfences:
      # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format

plugins:
    - search
    - mermaid2:
        arguments:
          securityLevel: 'loose'
          theme: forest # we want also that to work


theme:
  logo: assets/pbclogo.png
  favicon: assets/pbclogo_with_background.png
  name: material
  features:
    - toc.integrate
    - navigation.expand
    - navigation.sections
    - navigation.instant
